Peterbe/Peterbe/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Peterbe.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^computers/', include('computers.urls', namespace = "computers")),
)

Peterbe/computers/urls.py
from django.conf.urls import url, patterns
from computers import views

urlpatterns = patterns('',
	url(r'^$', views.index, name = "index"),
	url(r'^details/$', views.details, name = "details"),
)

Peterbe/computers/models.py
import datetime
	
from django.db import models
from django_mongokit import connection
from mongokit import Document

class Computer(Document):
	structure = {
		'make': unicode, 
		'model': unicode, 
		'purchase_date': unicode,
		'cpu_ghz': unicode,
	}
	
	validators = {
		'cpu_ghz': lambda x: x>0,
		'make': lambda x: x.strip(),
	}
	
	default_values = {
		'purchase_date': datetime.datetime.utcnow,
	}

	use_dot_notation = True
	
	indexes = [
		{'fields': ['make']},
	]
	
connection.register([Computer])

# Create your models here.

Peterbe/computers/views.py
from django.shortcuts import render
from django.http import HttpResponse
from mongokit import Connection
from computers.models import Computer

def index(request):
	return render(request, 'computers/index.html')

def details(request):
	if request.method == 'POST':
		if request.POST.get("computer_details"):
			print "You have successfully submitted the foem"
			conn = Connection()
			conn.register([Computer])
			database = conn.mydb
			collection = database.mycollection
			computer = collection.Computer()
			computer.make = unicode(request.POST['make'])
			computer.model = unicode(request.POST['model'])
			computer.purchase_date = unicode(request.POST['pur_date'])
			computer.cpu_ghz = unicode(request.POST['cpu_speed'])
			computer.save()
			print "Computer is:::" + str(computer.model)
			computer_list = collection.Computer.find()
			context = {'computer_list': computer_list}
			return render(request, 'computers/details.html', context)
			#return HttpResponse("Your response has been recorded")
		else:
			print "You havent clicked submit as yet"

	return HttpResponse("You response was not successfully recd")
			
	
		
# Create your views here.

Peterbe/computers/templates/computers/details.html
<html>
<head>
	<title> Computer Details </title>
</head>
<body>
{% if computer_list %}
<h3> The following are the computers available </h3>
<hr>

<ul>
	{% for computer in computer_list %}
	<li> Make:::: <strong> {{ computer.make }}</strong></li>
	<li> Model::: <strong> {{ computer.model }}</strong></li>
	<li> Purchase_date::: <strong> {{ computer.purchase_date }}</strong></li>
	<li> CPU Speed::: <strong> {{ computer.cpu_ghz }}</strong></li>
	<hr>
	{% endfor %}
</ul>
<h3> All these have unique Ids
</h3>



{% else %}
<h3> Sorry, no computers available at this moment </h3>
<hr>

 {% endif %}

</body>
</html>

Peterbe/computers/templates/computers/index.html
<html>
	<head>
		<title> Computer Page </title>
	</head>

<body>
	<h3> Pls register your vehicle here </h3>
	<hr>
	<p>

	<form action = "{% url 'computers:details' %}" method = "POST">
	{% csrf_token %}
		<ul>
			<li>Make:::: <input type = "text" name = "make" /></li>
			<li>Models::: <input type = "text" name = "model" /></li>
			<li>Purchase Date::: <input type = "text" name = "pur_date" /></li>
			<li>CPU Speed (Giga Hz)::: <input type = "text" name = "cpu_speed"/></li>
		</ul>

	<input type = "submit" name = "computer_details">
	</form>
	</p>
</body>
</html>