myFirstSite/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from polls import urls
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^$', 'mysite.views.home', name = 'home'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^polls/', include('polls.urls', namespace = "polls")),
	url(r'^poll_votes/', include('poll_votes.urls', namespace = "poll_votes")),
	
)

myFirstSite/mysite/poll_votes/urls.py
from django.conf.urls import patterns, url
from poll_votes import views
	
urlpatterns = patterns('', 
	url(r'^$', views.IndexView.as_view(), name = "index"), 
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name = "details"),
	url(r'^(?P<pk>\d+)/results/$', views.ResultView.as_view(), name = "results"),
	url(r'^(?P<poll_id>\d+)/votes/$', views.votes, name = "votes"),
)
	

myFirstSite/mysite/polls/urls.py
from django.conf.urls import url, patterns
	
from polls import views

urlpatterns = patterns('',
	url(r'^$', views.index, name = 'index'),
	url(r'^(?P<poll_id>\d+)/details/$', views.detail, name = 'poll_detail'),
	url(r'^(?P<poll_id>\d+)/results/$', views.results, name = 'poll_results'),
	url(r'^(?P<poll_id>\d+)/vote/$', views.votes, name = 'poll_votes'),
	
)

myFirstSite/mysite/mysite/poll_votes/models.py
from django.db import models

# Create your models here.

myFirstSite/mysite/poll_votes/models.py
from django.db import models

class Poll2(models.Model):
	question = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date published')
	
	def __unicode__(self):
		return self.question

	def was_published_recently(self):
		self.pub_date >= timezone.now() - datetime.timedelta(days=1)
		
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published Recently?'
	

class Choice2(models.Model):
	poll = models.ForeignKey(Poll2)
	choice_text = models.CharField(max_length = 200)
	votes = models.IntegerField(default =  0)

	def __unicode__(self):
		return "Text::" + self.choice_text + "::Votes::" + str(self.votes)



	
# Register your models here.

myFirstSite/mysite/polls/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Poll(models.Model):
	question = models.CharField(max_length = 200)
	pub_date = models.DateTimeField()
	#was_recently_published = models.BooleanField
	"""
	def __init__(self):
		self.was_recently_published = self.was_published_recently()	
	"""
	def __unicode__(self):
		return self.question
	
	def was_published_recently(self):
		return bool(timezone.now().month - self.pub_date.month < 1)


class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	#choice_text = models.CharField(max_length = 200)	
	votes = models.IntegerField(default = 0)
	choice_text = models.CharField(max_length = 200)

	def __unicode__(self):
		return self.choice_text	

myFirstSite/mysite/mysite/poll_votes/views.py
# Create your views here.

myFirstSite/mysite/mysite/views.py
from django.http import HttpResponse
	
def home(request):
	return HttpResponse("<H1>This is the home page</H1>")

myFirstSite/mysite/poll_votes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from poll_votes.models import Poll2, Choice2

class IndexView(generic.ListView):
        print "\n Inside IndexView \n"
        template_name = 'poll_votes/index.html'
        context_object_name = 'latest_poll_list'
        print "\ncontext_obj list:", context_object_name

        def get_queryset(self):	
                """Return the lst five published Polls"""
                print "\n inside get query\n"
        	return Poll2.objects.order_by('-pub_date')[:5]
        
class DetailView(generic.DetailView):
	model = Poll2
	#print "\n Poll2::question \n", Poll2.objects.all()
	#print "\n inside details view\n"
        #context_object_name = 'latest_poll_list'
	template_name = 'poll_votes/detail.html'
	

class ResultView(generic.DetailView):
	model = Poll2
	template_name = 'poll_votes/result.html'


def votes(request, poll_id):
	return HttpResponse("This is the results page")
	"""poll = get_object_or_404(Poll2, pk = poll_id)
	try:
		selected_choice = poll.choice_set.get(pk = request.POST['choice']
	except (KeyError, Choice2.DoesNotExist):
		return render(request, 'poll_votes/details.html',
			{'poll':poll,
			 'error_message':"You have not selected any choice. Kindly select one and then use it."
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		
		return HttpResponseRedirect(reverse('poll_votes/results.html', args = (poll.id,)))
		
"""

# Create your views here.

myFirstSite/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from polls.models import Poll, Choice
from django.template import RequestContext, loader
from django.http import Http404
from django.core.urlresolvers import reverse

"""
def index(request):
	latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
	template = loader.get_template('polls/index.html')
	context = RequestContext(request, {'latest_poll_list':latest_poll_list})
	return HttpResponse(template.render(context))
"""

def index(request):
	latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
	context = {'latest_poll_list': latest_poll_list}
	return render(request, 'polls/index.html', context)
"""	
def results(request, poll_id):
	return HttpResponse("This is the result for the poll number: %s" %poll_id)
"""
"""
def detail(request, poll_id):
	try:
		poll = Poll.objects.get(pk = poll_id)
	except:
		raise Http404
	return render(request, 'polls/detail.html', {'poll':poll})
"""

def detail(request, poll_id):
	poll = get_object_or_404(Poll, pk = poll_id)
	context = {'poll':poll}
	return render(request, 'polls/detail.html', context)	

def votes(request, poll_id):
	poll = get_object_or_404(Poll, pk = poll_id)
	try: 
 		selected_choice = poll.choice_set.get(pk = request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		context = {'poll':poll, 'error_message':"You did not select any choice. kindly select one"}
	
		return render(request, 'polls/detail.html', context)
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:poll_results', args = (poll.id,)))

def results(request, poll_id):
	poll = get_object_or_404(Poll, pk = poll_id)
	return render(request, 'polls/results.html', {'poll':poll})




# Create your views here.

myFirstSite/mysite/poll_votes/templates/poll_votes/detail.html
<p>This the poll detail for the poll_number: 
 {{poll.question}}
</p>
	
<ol type = "circle">
	{% for choice in poll.choice_set.all %}
		<li> {{ choice.choice_text }} </li>
	{% endfor %}
</ol>
	
{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}
<!--
<form action="{#% url 'poll_votes:votes' poll.id %#}" method = "post">
{#% csrf_token %#}
{#% for choice in poll.choice_set.all %#}
	<input type = "radio" name = "choice" id = "choice{{ forloop.counter }}" value = "{{ choice.id }}" />
	<label for = "choice{{ forloop.counter }}">
	{{ choice.choice_text }}
	</label>
	<br />
{#% endfor %#}
<input type = "submit" value = "Vote" />
</form>

-->

myFirstSite/mysite/poll_votes/templates/poll_votes/index.html
{% load staticfiles %}
	
<link rel = "stylesheet" type = "text/css" href = "{% static 'poll_votes/style.css' %}" />

<body>
{% if latest_poll_list %}
	<p> these are all the polls <br><br> </p>
	<ul>
	{% for poll in latest_poll_list %}
	<!--	<li><a href = "/polls/{{ poll.id }}/results">{{ poll.question }}</a></li>
	-->
	<li><a href = "{% url 'poll_votes:details' poll.id %}">{{ poll.question }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p> No Polls are available at this moment. </p>
{% endif %}
</body>

myFirstSite/mysite/poll_votes/templates/poll_votes/results.html
<h1>{{ poll.question }}</h1>
<ul>
	{% for choice in poll.choice_set.all %}
		<li>{{ choice.choice_text }} --- {{ choice.votes }} vote {{ choice.votes | pluralize }} </li>
	{% endfor %}
</ul>

<a href = "{% url 'poll_votes:details' poll.id %}">Vote Again? </a>

myFirstSite/mysite/polls/templates/polls/detail.html
<p>This the poll detail for the poll_number: 
 {{poll.question}}
</p>
	
<ol type = "circle">
	{% for choice in poll.choice_set.all %}
		<li> {{ choice.choice_text }} </li>
	{% endfor %}
</ol>
	
{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:poll_votes' poll.id %}" method = "post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
	<input type = "radio" name = "choice" id = "choice{{ forloop.counter }}" value = "{{ choice.id }}" />
	<label for = "choice{{ forloop.counter }}">
	{{ choice.choice_text }}
	</label>
	<br />
{% endfor %}
<input type = "submit" value = "Vote" />
</form>

myFirstSite/mysite/polls/templates/polls/index.html
{% load staticfiles %}
	
<link rel = "stylesheet" type = "text/css" href = "{% static 'polls/style.css' %}" />

<body>
{% if latest_poll_list %}
	<p> these are all the polls <br><br> </p>
	<ul>
	{% for poll in latest_poll_list %}
	<!--	<li><a href = "/polls/{{ poll.id }}/results">{{ poll.question }}</a></li>
	-->
	<li><a href = "{% url 'polls:poll_detail' poll.id %}">{{ poll.question }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p> No Polls are available at this moment. </p>
{% endif %}
</body>

myFirstSite/mysite/polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>
<ul>
	{% for choice in poll.choice_set.all %}
		<li>{{ choice.choice_text }} --- {{ choice.votes }} vote {{ choice.votes | pluralize }} </li>
	{% endfor %}
</ul>

<a href = "{% url 'polls:poll_detail' poll.id %}">Vote Again? </a>