AIC/AIC/urls.py
from django.conf.urls import patterns, include, url, static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'AIC.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	
    url(r'^admin/', include(admin.site.urls)),
    url(r'^companies/', include('companies.urls', namespace = "companies")),
) 
#+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AIC/companies/urls.py
from django.conf.urls import url, patterns

from companies import views
	
urlpatterns = patterns('', 
	url(r'^$', views.index, name = "index"),
	url(r'^(?P<company_id>\d+)/', views.details, name = "details"),
	url(r'^discipline/$', views.discipline, name = "discipline"),
	url(r'^discipline/(?P<discipline_id>\d+)/$', views.specific, name = "specific"),
	
)

AIC/companies/models.py
from django.db import models



class Discipline(models.Model):
	name = models.CharField(max_length = 100)
	text = models.CharField(max_length = 100)
		
	def __unicode__(self):
		return self.name


class Company(models.Model):
	discipline = models.ForeignKey(Discipline)
	name = models.CharField(max_length = 100)
	contact_name = models.CharField(max_length = 100)
	contact_phone = models.IntegerField(max_length = 10)
	logo = models.ImageField(upload_to = ('company_logo'), max_length = 50, blank = True)

	def __unicode__(self):
		return self.name

# Create your models here.

AIC/companies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from companies.models import Company, Discipline

def index(request):
	company_list = Company.objects.all()
	context = {'company_list': company_list}
	return render(request, 'companies/index.html', context)

def discipline(request):
	discipline_list = Discipline.objects.all()
	context = {'discipline_list': discipline_list}
	return render(request, 'companies/discipline.html', context)


def specific(request, discipline_id):

	company_list = Company.objects.filter(discipline = discipline_id)
	#print 'Companies' + str(company_list)
	context = {'company_list': company_list}
	return render(request, 'companies/specific.html', context)		

def details(request, company_id):
	company = get_object_or_404(Company, pk = company_id)
	context = {'company': company, 'companyname': company.name, 'companycontact_name': company.contact_name, 'companycontact_phone': company.contact_phone, 'companydiscipline': company.discipline}
	
	return render(request, 'companies/details.html', context)
	
	
	

# Create your views here.

AIC/companies/templates/companies/details.html
<H1> These are the details for the company:::::: {{ companyname }}</H1>

<H1> Contact Details:</H1>
<ul>
	<li><strong>Name:: </strong> {{ companycontact_name }}</li>

	<li><strong>Phone:: </strong> {{ companycontact_phone }} </li>
	
	<li><strong>Discipline:: </strong> {{ companydiscipline }} </li>

</ul>


<h1> You can apply when this turns into a link</h1>
<img src ="{{ MEDIA_URL }}{{ company.logo }}'%}" />
	

AIC/companies/templates/companies/discipline.html
{% if discipline_list %}
<H1> The foll are the categories of the AIC::</H1>
<ul>
	{% for discipline in discipline_list %}
	<li><a href = "{% url 'companies:specific' discipline.id %}">{{ discipline.name }}</a></li>
	{% endfor %}
</ul>

{% else %}
	
<H1> There are no disciplines added as of now </H1>

{% endif %}

AIC/companies/templates/companies/index.html
{% if company_list %}
<h1> these are the companies available for the AIC 2014 </h1>
	<ul>
		{% for company in company_list %}
		<li><a href = "{% url 'companies:details' company.id %}">{{ company.name }}</a></li>

		{% endfor %}
	</ul>
	




{% else %}
	
<h1> No companies have been added till now. </h1>


{% endif %}

AIC/companies/templates/companies/specific.html
{% if company_list %}
<H1> The foll are the companies of specific brach selected of the AIC::</H1>
<ul>
	{% for company in company_list %}
	<l1>{{ company.name }}</li>
	{% endfor %}
</ul>

{% else %}
	
<H1> There are no comanies for this branch added as of now </H1>

{% endif %}